---
kind: pipeline
name: default

steps:
  - name: Run rspec
    image: ruby:2.6.5
    environment:
      DATABASE_HOST: database
      RAILS_ENV: test
      VAULT_ADDR: http://vault:8200
    commands:
      - gem update bundler
      - bundle --jobs $(nproc)
      - rake db:create db:migrate
      - rspec spec/lib/arke

  - name: Bump and tag
    image: rubykube/robox:1.0.1
    environment:
      BOT_NAME: Kite
      BOT_EMAIL: kite-bot@heliostech.fr
      BOT_USERNAME: kite-bot
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - push.sh
    when:
      branch:
        - master

  - name: "First Docker build and push"
    image: plugins/gcr
    settings:
      repo:
        from_secret: gcr_repo_first
      json_key:
        from_secret: gcr_creds_base64_first
    when:
      branch:
        - master

  - name: "Second Docker build and push"
    image: plugins/gcr
    settings:
      repo:
        from_secret: gcr_repo_second
      json_key:
        from_secret: gcr_creds_base64_second
    when:
      branch:
        - master

  - name: "Push image to Quay.io"
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo: quay.io/openware/arke
      registry: quay.io
    when:
      branch:
        - master

services:
- name: database
  image: mariadb
  ports:
    - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

- name: vault
  image: vault:0.11.4
  ports:
    - 8200
  environment:
    SKIP_SETCAP: 1
    VAULT_TOKEN: changeme
    VAULT_DEV_ROOT_TOKEN_ID: changeme
    VAULT_ADDR: http://vault:8200

trigger:
  event:
    - push
