version: '3'

services:

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  redis:
    image: redis:4.0
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  vault:
    image: vault:0.11.4
    volumes:
      - vault_data:/vault
    ports:
      - "8200:8200"
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: changeme
      VAULT_DEV_ROOT_TOKEN_ID: changeme
      VAULT_ADDR: http://vault:8200

  influxdb:
    image: influxdb:1.7.8
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb
    environment:
       INFLUXDB_ADMIN_ENABLED: "true"

volumes:
  db_data:
  redis_data:
  vault_data:
  influx_data:
