default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
  username: <%= ENV.fetch("DATABASE_USER", "root") %>
  password: <%= ENV.fetch("DATABASE_PASS", "") %>

development:
  <<: *default
  database: arke_development

test:
  <<: *default
  database: arke_test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', "arke_production") %>
