default: &default
  host: <%= ENV.fetch("INFLUXDB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("INFLUXDB_PORT", 8083) %>
  username: <%= ENV.fetch("INFLUXDB_USER", "root") %>
  password: <%= ENV.fetch("INFLUXDB_PASS", "") %>

development:
  <<: *default
  database: arke_development

test:
  <<: *default
  database: arke_test

production:
  <<: *default
  database: <%= ENV.fetch('INFLUXDB_DATABASE_NAME', "arke_production") %>
