markets:
  - name:   BTCUSDT
    base:   BTC
    quote:  USDT
    base_precision: 8
    quote_precision: 2
  - name:   ETHUSDT
    base:   ETH
    quote:  USDT
    base_precision: 5
    quote_precision: 2

exchanges:
  - name: binance
    url:  "https://www.binance.com"
    rest: "https://api.binance.com"
    ws:   "wss://api.binance.com"
    rate: 1.0

  - name: bitfaker
    url:  ""
    rest: ""
    ws:   ""
    rate: 1.0

  - name: bitfinex
    url:  ""
    rest: ""
    ws:   ""
    rate: 1.0

  - name: hitbtc
    url:  ""
    rest: ""
    ws:   ""
    rate: 1.0

  - name: huobi
    url:  ""
    rest: ""
    ws:   ""
    rate: 1.0

  - name: kraken
    url:  ""
    rest: ""
    ws:   ""
    rate: 1.0

  - name: luno
    url:  ""
    rest: ""
    ws:   ""
    rate: 1.0

  - name: okex
    url:  ""
    rest: ""
    ws:   ""
    rate: 1.0

  - name: rubykube
    url:  "https://www.devkube.com"
    rest: "https://www.devkube.com"
    ws:   "wss://www.devkube.com"
    rate: 1.0
