log_level: INFO

accounts:
- id: demo
  driver: rubykube
  debug: false
  host: "https://demo.openware.com"
  ws: "wss://demo.openware.com"
  key: "df6330db624fcc67"
  secret: "c2ac593fd25281a4cbf9df6f88d700a0"
  delay: 1

- id: bitfaker
  driver: bitfaker
  delay: 1
  balances:
    btc: 3
    usd: 10000

- id: binance
  driver: binance
  debug: true
  delay: 1

- id: bitfinex
  driver: bitfinex
  delay: 1

- id: kraken
  driver: kraken
  delay: 1

strategies:
- id: copy-ETHUSD
  type: copy
  debug: true
  enabled: true
  period: 30
  params:
    spread_bids: 0.003
    spread_asks: 0.003
    limit_asks_base: 100
    limit_bids_base: 100
    max_amount_per_order: 0.5
    levels_size: 1
    levels_count: 10
    side: both
  target:
    account_id: demo
    market_id: ethusd

  sources:
  - account_id: kraken
    market_id: ETHUSD

- id: microtrades-FTHUSD
  type: microtrades
  debug: true
  enabled: false
  period: 5
  period_random_delay: 10
  params:
    linked_strategy_id: copy-FTHUSD
    min_amount: 0.05
    max_amount: 0.30
  target:
      account_id: demo
      market_id: ethusd
