log_level: DEBUG

accounts:
- id: demo
  driver: rubykube
  debug: false
  host: "https://demo.openware.com"
  ws: "wss://demo.openware.com"
  key: "bbd00510b6a40ad6"
  secret: "d8f3609b30491cd04f1d3b8ed99b4a37"
  delay: 0.1

- id: bitfaker
  driver: bitfaker
  delay: 1

- id: binance
  driver: binance
  debug: true
  delay: 1

- id: bitfinex
  driver: bitfinex
  delay: 1

strategies:
- id: copy-FTHUSD
  type: copy
  debug: true
  enabled: true
  period: 90
  params:
    spread_bids: 0.003
    spread_asks: 0.003
    limit_asks_base: 10
    limit_bids_base: 10
    levels_size: 0.25
    levels_count: 5
    side: both
  target:
    account_id: demo
    market:
      id: fthusd
      base: fth
      quote: usd
      base_precision: 2
      quote_precision: 2
      min_bid_amount: 0.01
      min_ask_amount: 0.01
  sources:
  - account_id: binance
    market:
      id: ETHUSDT
      base: ETH
      quote: USDT

- id: microtrades-FTHUSD
  type: microtrades
  debug: true
  enabled: true
  period: 5
  period_random_delay: 10
  params:
    linked_strategy_id: copy-FTHUSD
    min_amount: 0.05
    max_amount: 0.30
  target:
      account_id: demo
      market:
        id: fthusd
        base: fth
        quote: usd
        base_precision: 2
        quote_precision: 2
        min_ask_amount: 0.01
        min_bid_amount: 0.01
